/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/placeholder-scene.glb -o src/components/PlaceholderScene.jsx -r src/assets 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/placeholder-scene.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Planet_Placeholder.geometry} material={materials.Planet_Placeholder_mat} position={[0, -4, 0]} />
      <mesh geometry={nodes.Astronaut_Placeholder.geometry} material={materials.Astronaut_Placeholder_mat} position={[0, 0.4, 0]} />
    </group>
  )
}

useGLTF.preload('/placeholder-scene.glb')
